spring:
  application:
    name: service-registry-server

server:
  port: 8761
  tomcat:
    uri-encoding: UTF-8
    
eureka:
  instance:
    hostname: localhost
    port: ${server.port}
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  server:
    waitTimeInMsWhenSyncEmpty: 0

